# Generated by Django 4.2.1 on 2023-05-08 06:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('username', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskUUID', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('quadrant', models.TextField(max_length=20)),
                ('type', models.TextField(max_length=20)),
                ('content', models.TextField(max_length=100000)),
                ('icons', models.ImageField(null=True, upload_to='backend/icons')),
                ('due', models.DateTimeField(default=datetime.datetime.now)),
                ('reminder', models.DateTimeField(default=datetime.datetime.now)),
                ('creationdatetime', models.DateTimeField(default=datetime.datetime(2023, 5, 8, 6, 34, 59, 22313, tzinfo=datetime.timezone.utc))),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='backend/files')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
            options={
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
