# Generated by Django 4.2.1 on 2023-05-08 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creationdatetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 6, 35, 39, 807916, tzinfo=datetime.timezone.utc)),
        ),
    ]
