# Generated by Django 4.2 on 2023-04-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadrant', models.TextField(max_length=20)),
                ('type', models.TextField(max_length=20)),
                ('content', models.TextField(max_length=100000)),
            ],
        ),
    ]
