# Generated by Django 4.2 on 2023-05-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=123),
            preserve_default=False,
        ),
    ]
