# Generated by Django 4.2.1 on 2023-05-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_user_profile_alter_profile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='icons',
            new_name='icon',
        ),
    ]
