# Generated by Django 4.2 on 2023-05-06 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='uuid',
            new_name='taskUUID',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
    ]
