# Generated by Django 4.2 on 2023-05-06 04:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_uuid_task_taskuuid_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='userUUID',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
