# Generated by Django 4.2.1 on 2023-05-09 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_task_due_alter_task_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='content',
            new_name='subTaskContent',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='task',
            new_name='taskUUID',
        ),
        migrations.AddField(
            model_name='subtask',
            name='subTaskUUID',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
