# Generated by Django 4.2 on 2023-05-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_task_user_user_useruuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userUUID',
        ),
    ]
