# Generated by Django 4.2.1 on 2023-05-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_content_subtask_subtaskcontent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='taskUUID',
            new_name='task',
        ),
    ]
