# Generated by Django 4.2.1 on 2023-05-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_taskuuid_subtask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=models.ImageField(blank=True, default=213, upload_to='backend/icons'),
            preserve_default=False,
        ),
    ]
