# Generated by Django 4.2.1 on 2023-05-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_task_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=models.ImageField(blank=True, default='backend/icons/default/task.png', upload_to='backend/icons'),
        ),
    ]
